// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.bus.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.bus.dao.CategoryRuleDao;
import meg.bank.bus.dao.CategoryRuleDaoDataOnDemand;
import meg.bank.bus.repo.CategoryRuleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CategoryRuleDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CategoryRuleDaoDataOnDemand: @Component;
    
    private Random CategoryRuleDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<CategoryRuleDao> CategoryRuleDaoDataOnDemand.data;
    
    @Autowired
    CategoryRuleRepository CategoryRuleDaoDataOnDemand.categoryRuleRepository;
    
    public CategoryRuleDao CategoryRuleDaoDataOnDemand.getNewTransientCategoryRuleDao(int index) {
        CategoryRuleDao obj = new CategoryRuleDao();
        return obj;
    }
    
    public CategoryRuleDao CategoryRuleDaoDataOnDemand.getSpecificCategoryRuleDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CategoryRuleDao obj = data.get(index);
        Long id = obj.getId();
        return categoryRuleRepository.findOne(id);
    }
    
    public CategoryRuleDao CategoryRuleDaoDataOnDemand.getRandomCategoryRuleDao() {
        init();
        CategoryRuleDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return categoryRuleRepository.findOne(id);
    }
    
    public boolean CategoryRuleDaoDataOnDemand.modifyCategoryRuleDao(CategoryRuleDao obj) {
        return false;
    }
    
    public void CategoryRuleDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = categoryRuleRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CategoryRuleDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CategoryRuleDao>();
        for (int i = 0; i < 10; i++) {
            CategoryRuleDao obj = getNewTransientCategoryRuleDao(i);
            try {
                categoryRuleRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            categoryRuleRepository.flush();
            data.add(obj);
        }
    }
    
}
