// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.bus.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.bus.dao.CatRelationshipDao;
import meg.bank.bus.dao.CatRelationshipDaoDataOnDemand;
import meg.bank.bus.repo.CatRelationshipRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect CatRelationshipDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CatRelationshipDaoDataOnDemand: @Component;
    
    private Random CatRelationshipDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<CatRelationshipDao> CatRelationshipDaoDataOnDemand.data;
    
    @Autowired
    CatRelationshipRepository CatRelationshipDaoDataOnDemand.catRelationshipRepository;
    
    public CatRelationshipDao CatRelationshipDaoDataOnDemand.getNewTransientCatRelationshipDao(int index) {
        CatRelationshipDao obj = new CatRelationshipDao();
        setChildId(obj, index);
        setParentId(obj, index);
        return obj;
    }
    
    public void CatRelationshipDaoDataOnDemand.setChildId(CatRelationshipDao obj, int index) {
        Long childId = new Integer(index).longValue();
        obj.setChildId(childId);
    }
    
    public void CatRelationshipDaoDataOnDemand.setParentId(CatRelationshipDao obj, int index) {
        Long parentId = new Integer(index).longValue();
        obj.setParentId(parentId);
    }
    
    public CatRelationshipDao CatRelationshipDaoDataOnDemand.getSpecificCatRelationshipDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        CatRelationshipDao obj = data.get(index);
        Long id = obj.getId();
        return catRelationshipRepository.findOne(id);
    }
    
    public CatRelationshipDao CatRelationshipDaoDataOnDemand.getRandomCatRelationshipDao() {
        init();
        CatRelationshipDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return catRelationshipRepository.findOne(id);
    }
    
    public boolean CatRelationshipDaoDataOnDemand.modifyCatRelationshipDao(CatRelationshipDao obj) {
        return false;
    }
    
    public void CatRelationshipDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = catRelationshipRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'CatRelationshipDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<CatRelationshipDao>();
        for (int i = 0; i < 10; i++) {
            CatRelationshipDao obj = getNewTransientCatRelationshipDao(i);
            try {
                catRelationshipRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            catRelationshipRepository.flush();
            data.add(obj);
        }
    }
    
}
