// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.bus.dao;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.bus.dao.ExpenseDaoDataOnDemand;
import meg.bank.bus.dao.ExpenseDaoIntegrationTest;
import meg.bank.bus.repo.ExpenseRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ExpenseDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ExpenseDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ExpenseDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ExpenseDaoIntegrationTest: @Transactional;
    
    @Autowired
    ExpenseDaoDataOnDemand ExpenseDaoIntegrationTest.dod;
    
    @Autowired
    ExpenseRepository ExpenseDaoIntegrationTest.expenseRepository;
    
    @Test
    public void ExpenseDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", dod.getRandomExpenseDao());
        long count = expenseRepository.count();
        Assert.assertTrue("Counter for 'ExpenseDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testFind() {
        ExpenseDao obj = dod.getRandomExpenseDao();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to provide an identifier", id);
        obj = expenseRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ExpenseDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ExpenseDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", dod.getRandomExpenseDao());
        long count = expenseRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ExpenseDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ExpenseDao> result = expenseRepository.findAll();
        Assert.assertNotNull("Find all method for 'ExpenseDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ExpenseDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", dod.getRandomExpenseDao());
        long count = expenseRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ExpenseDao> result = expenseRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ExpenseDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ExpenseDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testFlush() {
        ExpenseDao obj = dod.getRandomExpenseDao();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to provide an identifier", id);
        obj = expenseRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ExpenseDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyExpenseDao(obj);
        Integer currentVersion = obj.getVersion();
        expenseRepository.flush();
        Assert.assertTrue("Version for 'ExpenseDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testSaveUpdate() {
        ExpenseDao obj = dod.getRandomExpenseDao();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to provide an identifier", id);
        obj = expenseRepository.findOne(id);
        boolean modified =  dod.modifyExpenseDao(obj);
        Integer currentVersion = obj.getVersion();
        ExpenseDao merged = expenseRepository.save(obj);
        expenseRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ExpenseDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", dod.getRandomExpenseDao());
        ExpenseDao obj = dod.getNewTransientExpenseDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ExpenseDao' identifier to be null", obj.getId());
        try {
            expenseRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        expenseRepository.flush();
        Assert.assertNotNull("Expected 'ExpenseDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ExpenseDaoIntegrationTest.testDelete() {
        ExpenseDao obj = dod.getRandomExpenseDao();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ExpenseDao' failed to provide an identifier", id);
        obj = expenseRepository.findOne(id);
        expenseRepository.delete(obj);
        expenseRepository.flush();
        Assert.assertNull("Failed to remove 'ExpenseDao' with identifier '" + id + "'", expenseRepository.findOne(id));
    }
    
}
