// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.bus.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.bus.dao.QuickGroup;
import meg.bank.bus.dao.QuickGroupDataOnDemand;
import meg.bank.bus.repo.QuickGroupRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect QuickGroupDataOnDemand_Roo_DataOnDemand {
    
    declare @type: QuickGroupDataOnDemand: @Component;
    
    private Random QuickGroupDataOnDemand.rnd = new SecureRandom();
    
    private List<QuickGroup> QuickGroupDataOnDemand.data;
    
    @Autowired
    QuickGroupRepository QuickGroupDataOnDemand.quickGroupRepository;
    
    public QuickGroup QuickGroupDataOnDemand.getNewTransientQuickGroup(int index) {
        QuickGroup obj = new QuickGroup();
        setName(obj, index);
        return obj;
    }
    
    public void QuickGroupDataOnDemand.setName(QuickGroup obj, int index) {
        String name = "name_" + index;
        if (name.length() > 100) {
            name = name.substring(0, 100);
        }
        obj.setName(name);
    }
    
    public QuickGroup QuickGroupDataOnDemand.getSpecificQuickGroup(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        QuickGroup obj = data.get(index);
        Long id = obj.getId();
        return quickGroupRepository.findOne(id);
    }
    
    public QuickGroup QuickGroupDataOnDemand.getRandomQuickGroup() {
        init();
        QuickGroup obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return quickGroupRepository.findOne(id);
    }
    
    public boolean QuickGroupDataOnDemand.modifyQuickGroup(QuickGroup obj) {
        return false;
    }
    
    public void QuickGroupDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = quickGroupRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'QuickGroup' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<QuickGroup>();
        for (int i = 0; i < 10; i++) {
            QuickGroup obj = getNewTransientQuickGroup(i);
            try {
                quickGroupRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            quickGroupRepository.flush();
            data.add(obj);
        }
    }
    
}
