// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.bus.dao;

import meg.bank.bus.dao.TargetDetailDaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TargetDetailDaoIntegrationTest_Roo_Configurable {
    
    declare @type: TargetDetailDaoIntegrationTest: @Configurable;
    
}
