// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.util.common.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.util.common.db.ColumnKeyDao;
import meg.bank.util.common.repo.ColumnKeyRepository;
import meg.util.common.dao.ColumnKeyDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ColumnKeyDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ColumnKeyDaoDataOnDemand: @Component;
    
    private Random ColumnKeyDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<ColumnKeyDao> ColumnKeyDaoDataOnDemand.data;
    
    @Autowired
    ColumnKeyRepository ColumnKeyDaoDataOnDemand.columnKeyRepository;
    
    public ColumnKeyDao ColumnKeyDaoDataOnDemand.getNewTransientColumnKeyDao(int index) {
        ColumnKeyDao obj = new ColumnKeyDao();
        setLookup(obj, index);
        return obj;
    }
    
    public void ColumnKeyDaoDataOnDemand.setLookup(ColumnKeyDao obj, int index) {
        String lookup = "lookup_" + index;
        if (lookup.length() > 100) {
            lookup = lookup.substring(0, 100);
        }
        obj.setLookup(lookup);
    }
    
    public ColumnKeyDao ColumnKeyDaoDataOnDemand.getSpecificColumnKeyDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ColumnKeyDao obj = data.get(index);
        Long id = obj.getId();
        return columnKeyRepository.findOne(id);
    }
    
    public ColumnKeyDao ColumnKeyDaoDataOnDemand.getRandomColumnKeyDao() {
        init();
        ColumnKeyDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return columnKeyRepository.findOne(id);
    }
    
    public boolean ColumnKeyDaoDataOnDemand.modifyColumnKeyDao(ColumnKeyDao obj) {
        return false;
    }
    
    public void ColumnKeyDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = columnKeyRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ColumnKeyDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ColumnKeyDao>();
        for (int i = 0; i < 10; i++) {
            ColumnKeyDao obj = getNewTransientColumnKeyDao(i);
            try {
                columnKeyRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            columnKeyRepository.flush();
            data.add(obj);
        }
    }
    
}
