// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.util.common.dao;

import java.util.Iterator;
import java.util.List;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import meg.bank.util.common.db.ColumnValueDao;
import meg.bank.util.common.repo.ColumnValueRepository;
import meg.util.common.dao.ColumnValueDaoDataOnDemand;
import meg.util.common.dao.ColumnValueDaoIntegrationTest;

import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ColumnValueDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ColumnValueDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ColumnValueDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ColumnValueDaoIntegrationTest: @Transactional;
    
    @Autowired
    ColumnValueDaoDataOnDemand ColumnValueDaoIntegrationTest.dod;
    
    @Autowired
    ColumnValueRepository ColumnValueDaoIntegrationTest.columnValueRepository;
    
    @Test
    public void ColumnValueDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", dod.getRandomColumnValueDao());
        long count = columnValueRepository.count();
        Assert.assertTrue("Counter for 'ColumnValueDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testFind() {
        ColumnValueDao obj = dod.getRandomColumnValueDao();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to provide an identifier", id);
        obj = columnValueRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ColumnValueDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ColumnValueDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", dod.getRandomColumnValueDao());
        long count = columnValueRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ColumnValueDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ColumnValueDao> result = columnValueRepository.findAll();
        Assert.assertNotNull("Find all method for 'ColumnValueDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ColumnValueDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", dod.getRandomColumnValueDao());
        long count = columnValueRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ColumnValueDao> result = columnValueRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ColumnValueDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ColumnValueDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testFlush() {
        ColumnValueDao obj = dod.getRandomColumnValueDao();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to provide an identifier", id);
        obj = columnValueRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ColumnValueDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyColumnValueDao(obj);
        Integer currentVersion = obj.getVersion();
        columnValueRepository.flush();
        Assert.assertTrue("Version for 'ColumnValueDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testSaveUpdate() {
        ColumnValueDao obj = dod.getRandomColumnValueDao();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to provide an identifier", id);
        obj = columnValueRepository.findOne(id);
        boolean modified =  dod.modifyColumnValueDao(obj);
        Integer currentVersion = obj.getVersion();
        ColumnValueDao merged = columnValueRepository.save(obj);
        columnValueRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ColumnValueDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", dod.getRandomColumnValueDao());
        ColumnValueDao obj = dod.getNewTransientColumnValueDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ColumnValueDao' identifier to be null", obj.getId());
        try {
            columnValueRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        columnValueRepository.flush();
        Assert.assertNotNull("Expected 'ColumnValueDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ColumnValueDaoIntegrationTest.testDelete() {
        ColumnValueDao obj = dod.getRandomColumnValueDao();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnValueDao' failed to provide an identifier", id);
        obj = columnValueRepository.findOne(id);
        columnValueRepository.delete(obj);
        columnValueRepository.flush();
        Assert.assertNull("Failed to remove 'ColumnValueDao' with identifier '" + id + "'", columnValueRepository.findOne(id));
    }
    
}
