// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.util.common.dao;

import meg.util.common.dao.ColumnValueDaoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ColumnValueDaoDataOnDemand_Roo_Configurable {
    
    declare @type: ColumnValueDaoDataOnDemand: @Configurable;
    
}
