// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.util.common.dao;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;

import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;

import meg.bank.util.common.db.ColumnValueDao;
import meg.bank.util.common.repo.ColumnValueRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ColumnValueDaoDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ColumnValueDaoDataOnDemand: @Component;
    
    private Random ColumnValueDaoDataOnDemand.rnd = new SecureRandom();
    
    private List<ColumnValueDao> ColumnValueDaoDataOnDemand.data;
    
    @Autowired
    ColumnKeyDaoDataOnDemand ColumnValueDaoDataOnDemand.columnKeyDaoDataOnDemand;
    
    @Autowired
    ColumnValueRepository ColumnValueDaoDataOnDemand.columnValueRepository;
    
    public ColumnValueDao ColumnValueDaoDataOnDemand.getNewTransientColumnValueDao(int index) {
        ColumnValueDao obj = new ColumnValueDao();
        setActive(obj, index);
        setDisplay(obj, index);
        setDisporder(obj, index);
        setValue(obj, index);
        return obj;
    }
    
    public void ColumnValueDaoDataOnDemand.setActive(ColumnValueDao obj, int index) {
        Boolean active = Boolean.TRUE;
        obj.setActive(active);
    }
    
    public void ColumnValueDaoDataOnDemand.setDisplay(ColumnValueDao obj, int index) {
        String display = "display_" + index;
        if (display.length() > 100) {
            display = display.substring(0, 100);
        }
        obj.setDisplay(display);
    }
    
    public void ColumnValueDaoDataOnDemand.setDisporder(ColumnValueDao obj, int index) {
        Long disporder = new Integer(index).longValue();
        obj.setDisporder(disporder);
    }
    
    public void ColumnValueDaoDataOnDemand.setValue(ColumnValueDao obj, int index) {
        String value = "value_" + index;
        if (value.length() > 100) {
            value = value.substring(0, 100);
        }
        obj.setValue(value);
    }
    
    public ColumnValueDao ColumnValueDaoDataOnDemand.getSpecificColumnValueDao(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ColumnValueDao obj = data.get(index);
        Long id = obj.getId();
        return columnValueRepository.findOne(id);
    }
    
    public ColumnValueDao ColumnValueDaoDataOnDemand.getRandomColumnValueDao() {
        init();
        ColumnValueDao obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return columnValueRepository.findOne(id);
    }
    
    public boolean ColumnValueDaoDataOnDemand.modifyColumnValueDao(ColumnValueDao obj) {
        return false;
    }
    
    public void ColumnValueDaoDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = columnValueRepository.findAll(new org.springframework.data.domain.PageRequest(from / to, to)).getContent();
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ColumnValueDao' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ColumnValueDao>();
        for (int i = 0; i < 10; i++) {
            ColumnValueDao obj = getNewTransientColumnValueDao(i);
            try {
                columnValueRepository.save(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            columnValueRepository.flush();
            data.add(obj);
        }
    }
    
}
