// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.util.common.db;

import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import meg.bank.util.common.db.ColumnKeyDaoDataOnDemand;
import meg.bank.util.common.db.ColumnKeyDaoIntegrationTest;
import meg.bank.util.common.repo.ColumnKeyRepository;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ColumnKeyDaoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ColumnKeyDaoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ColumnKeyDaoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ColumnKeyDaoIntegrationTest: @Transactional;
    
    @Autowired
    ColumnKeyDaoDataOnDemand ColumnKeyDaoIntegrationTest.dod;
    
    @Autowired
    ColumnKeyRepository ColumnKeyDaoIntegrationTest.columnKeyRepository;
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testCount() {
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", dod.getRandomColumnKeyDao());
        long count = columnKeyRepository.count();
        Assert.assertTrue("Counter for 'ColumnKeyDao' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testFind() {
        ColumnKeyDao obj = dod.getRandomColumnKeyDao();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to provide an identifier", id);
        obj = columnKeyRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ColumnKeyDao' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ColumnKeyDao' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testFindAll() {
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", dod.getRandomColumnKeyDao());
        long count = columnKeyRepository.count();
        Assert.assertTrue("Too expensive to perform a find all test for 'ColumnKeyDao', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ColumnKeyDao> result = columnKeyRepository.findAll();
        Assert.assertNotNull("Find all method for 'ColumnKeyDao' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ColumnKeyDao' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testFindEntries() {
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", dod.getRandomColumnKeyDao());
        long count = columnKeyRepository.count();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ColumnKeyDao> result = columnKeyRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
        Assert.assertNotNull("Find entries method for 'ColumnKeyDao' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ColumnKeyDao' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testFlush() {
        ColumnKeyDao obj = dod.getRandomColumnKeyDao();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to provide an identifier", id);
        obj = columnKeyRepository.findOne(id);
        Assert.assertNotNull("Find method for 'ColumnKeyDao' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyColumnKeyDao(obj);
        Integer currentVersion = obj.getVersion();
        columnKeyRepository.flush();
        Assert.assertTrue("Version for 'ColumnKeyDao' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testSaveUpdate() {
        ColumnKeyDao obj = dod.getRandomColumnKeyDao();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to provide an identifier", id);
        obj = columnKeyRepository.findOne(id);
        boolean modified =  dod.modifyColumnKeyDao(obj);
        Integer currentVersion = obj.getVersion();
        ColumnKeyDao merged = columnKeyRepository.save(obj);
        columnKeyRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ColumnKeyDao' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testSave() {
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", dod.getRandomColumnKeyDao());
        ColumnKeyDao obj = dod.getNewTransientColumnKeyDao(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ColumnKeyDao' identifier to be null", obj.getId());
        try {
            columnKeyRepository.save(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        columnKeyRepository.flush();
        Assert.assertNotNull("Expected 'ColumnKeyDao' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ColumnKeyDaoIntegrationTest.testDelete() {
        ColumnKeyDao obj = dod.getRandomColumnKeyDao();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ColumnKeyDao' failed to provide an identifier", id);
        obj = columnKeyRepository.findOne(id);
        columnKeyRepository.delete(obj);
        columnKeyRepository.flush();
        Assert.assertNull("Failed to remove 'ColumnKeyDao' with identifier '" + id + "'", columnKeyRepository.findOne(id));
    }
    
}
