// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package meg.bank.util.common.db;

import meg.bank.util.common.db.ColumnKeyDaoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ColumnKeyDaoIntegrationTest_Roo_Configurable {
    
    declare @type: ColumnKeyDaoIntegrationTest: @Configurable;
    
}
